# Generated by Django 3.0.5 on 2020-04-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_object', models.URLField(blank=True)),
                ('metro_distance', models.CharField(blank=True, max_length=50)),
                ('metro_distance_number', models.CharField(blank=True, max_length=32)),
                ('total_square', models.CharField(blank=True, max_length=32)),
                ('living_square', models.CharField(blank=True, max_length=32)),
                ('floor_number', models.CharField(blank=True, max_length=32)),
                ('floor_total', models.CharField(blank=True, max_length=32)),
                ('is_home_appliances', models.CharField(blank=True, max_length=32)),
                ('is_furniture', models.CharField(blank=True, max_length=32)),
                ('year_public', models.CharField(blank=True, max_length=32)),
                ('month_public', models.CharField(blank=True, max_length=32)),
                ('day_public', models.CharField(blank=True, max_length=32)),
                ('time_public', models.CharField(blank=True, max_length=16)),
                ('cost', models.CharField(blank=True, max_length=32)),
                ('house_number', models.CharField(blank=True, max_length=32)),
                ('advertising_object', models.CharField(blank=True, max_length=70)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('сreator', models.CharField(blank=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Area_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Balcony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Message_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Images_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.URLField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='area_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Area_city'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='balcony_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Balcony'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.ManyToManyField(to='realtyapp.Category'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Sity'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='count_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Room_count'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Currency'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Images'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Material'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='metro_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Metro'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtyapp.Street'),
        ),
    ]
